[package]
name = "nr-model"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["nr-tensor/std"]

[dependencies]
libm = "0.2"
nr-tensor = { path = "../nr-tensor", default-features = false }
nr-token = { path = "../nr-token", default-features = false }

[dev-dependencies]
nr-token = { path = "../nr-token" }
