//! Encode reference cases (generated by scripts/gen_tokenizer_fixtures.py
//! with the official HF tokenizer) and compare token ids exactly.
//!
//! Requires models/model.nrm (built by nrconvert); skips when absent.

use std::io::{Read, Seek, SeekFrom};

fn read_tokenizer_blob() -> Option<Vec<u8>> {
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");
    let mut f = std::fs::File::open(format!("{root}/models/model.nrm")).ok()?;
    // Header: tok_off u64 at 116, tok_size u64 at 124 (see nr-model::format).
    let mut header = [0u8; 172];
    f.read_exact(&mut header).ok()?;
    assert_eq!(&header[0..4], b"NRUN");
    let tok_off = u64::from_le_bytes(header[116..124].try_into().unwrap());
    let tok_size = u64::from_le_bytes(header[124..132].try_into().unwrap());
    let mut blob = vec![0u8; tok_size as usize];
    f.seek(SeekFrom::Start(tok_off)).ok()?;
    f.read_exact(&mut blob).ok()?;
    Some(blob)
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn matches_reference_tokenizer() {
    let Some(blob) = read_tokenizer_blob() else {
        eprintln!("SKIP: models/model.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");

    let fixtures = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/fixtures/tokenizer_cases.txt");
    let data = std::fs::read_to_string(fixtures).expect("fixtures file");
    let mut failures = 0;
    let mut total = 0;
    for line in data.lines() {
        let (hex, ids_s) = line.split_once('\t').unwrap();
        let text = String::from_utf8(unhex(hex)).unwrap();
        let expect: Vec<u32> = if ids_s.is_empty() {
            vec![]
        } else {
            ids_s.split(',').map(|v| v.parse().unwrap()).collect()
        };
        let mut got = Vec::new();
        tok.encode_text(&text, &mut got);
        total += 1;
        if got != expect {
            failures += 1;
            eprintln!("MISMATCH {text:?}\n  expect {expect:?}\n  got    {got:?}");
        }
    }
    assert_eq!(failures, 0, "{failures}/{total} tokenizer cases mismatched");
}

#[test]
fn decode_roundtrip() {
    let Some(blob) = read_tokenizer_blob() else {
        eprintln!("SKIP: models/model.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");
    let text = "NightRun boots Llama 3.2 on bare metal — 1980s neon vibes! 🌆";
    let mut ids = Vec::new();
    tok.encode_text(text, &mut ids);
    let mut bytes = Vec::new();
    for &id in &ids {
        bytes.extend_from_slice(tok.token_bytes(id));
    }
    assert_eq!(String::from_utf8(bytes).unwrap(), text);
}

#[test]
fn specials_are_wired() {
    let Some(blob) = read_tokenizer_blob() else {
        eprintln!("SKIP: models/model.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");
    let s = tok.specials;
    assert_eq!(s.bos, 128000);
    assert_eq!(s.end_of_text, 128001);
    assert_eq!(s.start_header, 128006);
    assert_eq!(s.end_header, 128007);
    assert_eq!(s.eot, 128009);
    assert!(tok.is_stop(s.eot));
    assert!(tok.is_control(s.bos));
    assert!(!tok.is_control(9906));

    // Chat template shape: <|start_header_id|>user<|end_header_id|>\n\n
    let mut ids = Vec::new();
    tok.encode_header("user", &mut ids);
    assert_eq!(ids[0], s.start_header);
    assert_eq!(ids[ids.len() - 2], s.end_header);
}
