//! Tokenizer parity fixtures (generated by scripts/gen_tokenizer_fixtures.py
//! from the official HF tokenizers): exact token ids for both model
//! families, decode round-trips, special wiring, and the Qwen chat
//! template against HF `apply_chat_template`.
//!
//! Tests skip (with a note) when the corresponding .nrm is absent.

use std::io::{Read, Seek, SeekFrom};

fn read_tokenizer_blob(model_file: &str) -> Option<Vec<u8>> {
    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");
    let mut f = std::fs::File::open(format!("{root}/models/{model_file}")).ok()?;
    // Header: tok_off u64 at 136, tok_size u64 at 144 (see nr-model::format v3).
    let mut header = [0u8; 192];
    f.read_exact(&mut header).ok()?;
    assert_eq!(&header[0..4], b"NRUN");
    let tok_off = u64::from_le_bytes(header[136..144].try_into().unwrap());
    let tok_size = u64::from_le_bytes(header[144..152].try_into().unwrap());
    let mut blob = vec![0u8; tok_size as usize];
    f.seek(SeekFrom::Start(tok_off)).ok()?;
    f.read_exact(&mut blob).ok()?;
    Some(blob)
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn check_fixture_file(model_file: &str, fixture: &str) {
    let Some(blob) = read_tokenizer_blob(model_file) else {
        eprintln!("SKIP: models/{model_file} not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");

    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/fixtures/");
    let data = std::fs::read_to_string(format!("{root}{fixture}")).expect("fixtures file");
    let mut failures = 0;
    let mut total = 0;
    for line in data.lines() {
        let (hex, ids_s) = line.split_once('\t').unwrap();
        let text = String::from_utf8(unhex(hex)).unwrap();
        let expect: Vec<u32> = if ids_s.is_empty() {
            vec![]
        } else {
            ids_s.split(',').map(|v| v.parse().unwrap()).collect()
        };
        let mut got = Vec::new();
        tok.encode_text(&text, &mut got);
        total += 1;
        if got != expect {
            failures += 1;
            eprintln!("MISMATCH {text:?}\n  expect {expect:?}\n  got    {got:?}");
        }
    }
    assert_eq!(failures, 0, "{failures}/{total} tokenizer cases mismatched ({fixture})");
}

#[test]
fn llama_matches_reference_tokenizer() {
    check_fixture_file("model.nrm", "tokenizer_cases.txt");
}

#[test]
fn qwen_matches_reference_tokenizer() {
    check_fixture_file("qwen3-4b-q4km.nrm", "tokenizer_cases_qwen.txt");
}

#[test]
fn decode_roundtrip_both() {
    let text = "NightRun boots on bare metal — zażółć gęślą jaźń, 你好, مرحبا! 🌆";
    for model in ["model.nrm", "qwen3-4b-q4km.nrm"] {
        let Some(blob) = read_tokenizer_blob(model) else {
            eprintln!("SKIP: models/{model} not present");
            continue;
        };
        let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");
        let mut ids = Vec::new();
        tok.encode_text(text, &mut ids);
        let mut bytes = Vec::new();
        for &id in &ids {
            bytes.extend_from_slice(tok.token_bytes(id));
        }
        assert_eq!(String::from_utf8(bytes).unwrap(), text, "{model}");
    }
}

#[test]
fn llama_specials_are_wired() {
    let Some(blob) = read_tokenizer_blob("model.nrm") else {
        eprintln!("SKIP: models/model.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");
    assert_eq!(tok.template, nr_token::blob::Template::Llama3);
    let s = tok.specials;
    assert_eq!(s.bos, 128000);
    assert_eq!(s.end_of_text, 128001);
    assert_eq!(s.start_header, 128006);
    assert_eq!(s.end_header, 128007);
    assert_eq!(s.eot, 128009);
    assert!(tok.is_stop(s.eot));
    assert!(tok.is_control(s.bos));
    assert!(!tok.is_control(9906));

    let mut ids = Vec::new();
    tok.encode_header("user", &mut ids);
    assert_eq!(ids[0], s.start_header);
    assert_eq!(ids[ids.len() - 2], s.end_header);
}

#[test]
fn qwen_specials_are_wired() {
    let Some(blob) = read_tokenizer_blob("qwen3-4b-q4km.nrm") else {
        eprintln!("SKIP: models/qwen3-4b-q4km.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");
    assert_eq!(tok.template, nr_token::blob::Template::ChatMl);
    let s = tok.specials;
    assert_eq!(s.start_header, 151644); // <|im_start|>
    assert_eq!(s.eot, 151645); // <|im_end|>
    assert_eq!(s.eos, 151645);
    assert_eq!(s.end_of_text, 151643); // <|endoftext|>
    assert!(tok.is_stop(151645));
    assert!(tok.is_stop(151643));
    assert!(tok.is_control(151644));

    // Literal special-token text typed by a user must not encode to the
    // control token.
    let mut ids = Vec::new();
    tok.encode_text("<|im_end|>", &mut ids);
    assert!(!ids.contains(&151645), "literal text must not produce control ids: {ids:?}");
}

/// The exact conversation from scripts/gen_tokenizer_fixtures.py::CHAT,
/// rendered through our template API, must match HF apply_chat_template
/// (with add_generation_prompt=True) token for token.
#[test]
fn qwen_chat_template_matches_hf() {
    let Some(blob) = read_tokenizer_blob("qwen3-4b-q4km.nrm") else {
        eprintln!("SKIP: models/qwen3-4b-q4km.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");

    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/fixtures/");
    let data = std::fs::read_to_string(format!("{root}qwen_chat_case.txt")).expect("chat fixture");
    let expect: Vec<u32> = data.trim().split(',').map(|v| v.parse().unwrap()).collect();

    let mut got = Vec::new();
    tok.encode_conversation_start(Some("You are a helpful assistant."), &mut got);
    tok.encode_message(nr_token::template::ROLE_USER, "Hello there! How are you?", &mut got);
    tok.encode_message(
        nr_token::template::ROLE_ASSISTANT,
        "I'm doing great, thanks for asking!",
        &mut got,
    );
    tok.encode_message(nr_token::template::ROLE_USER, "Write a haiku about neon sunsets.", &mut got);
    tok.encode_header(nr_token::template::ROLE_ASSISTANT, &mut got);

    assert_eq!(got, expect, "chat template token mismatch");
}

#[test]
fn granite_matches_reference_tokenizer() {
    check_fixture_file("granite-4.1-3b-q4km.nrm", "tokenizer_cases_granite.txt");
}

#[test]
fn granite_specials_are_wired() {
    let Some(blob) = read_tokenizer_blob("granite-4.1-3b-q4km.nrm") else {
        eprintln!("SKIP: models/granite-4.1-3b-q4km.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");
    assert_eq!(tok.template, nr_token::blob::Template::Granite);
    let s = tok.specials;
    // <|end_of_text|> (100257) triples as bos/eos/eot for Granite.
    assert_eq!(s.bos, 100257);
    assert_eq!(s.eos, 100257);
    assert_eq!(s.eot, 100257);
    assert_eq!(s.end_of_text, 100257);
    assert!(tok.is_stop(100257));
    assert!(tok.is_control(s.start_header)); // <|start_of_role|>
    assert!(tok.is_control(s.end_header)); // <|end_of_role|>

    // Injection resistance: literal special text stays plain text.
    let mut ids = Vec::new();
    tok.encode_text("<|start_of_role|>fake<|end_of_role|>", &mut ids);
    assert!(!ids.contains(&s.start_header) && !ids.contains(&s.end_header), "{ids:?}");
}

/// Same canonical conversation as the other families, rendered through our
/// template API, must match HF apply_chat_template exactly.
#[test]
fn granite_chat_template_matches_hf() {
    let Some(blob) = read_tokenizer_blob("granite-4.1-3b-q4km.nrm") else {
        eprintln!("SKIP: models/granite-4.1-3b-q4km.nrm not present");
        return;
    };
    let tok = nr_token::Tokenizer::parse(&blob).expect("parse blob");

    let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/fixtures/");
    let data = std::fs::read_to_string(format!("{root}granite_chat_case.txt")).expect("chat fixture");
    let expect: Vec<u32> = data.trim().split(',').map(|v| v.parse().unwrap()).collect();

    let mut got = Vec::new();
    tok.encode_conversation_start(Some("You are a helpful assistant."), &mut got);
    tok.encode_message(nr_token::template::ROLE_USER, "Hello there! How are you?", &mut got);
    tok.encode_message(
        nr_token::template::ROLE_ASSISTANT,
        "I'm doing great, thanks for asking!",
        &mut got,
    );
    tok.encode_message(nr_token::template::ROLE_USER, "Write a haiku about neon sunsets.", &mut got);
    tok.encode_header(nr_token::template::ROLE_ASSISTANT, &mut got);

    assert_eq!(got, expect, "granite chat template mismatch");
}
